//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace ARChess.ARVR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ARVR.IARVR")]
    public interface IARVR {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IARVR/RecognizeSpeech", ReplyAction="http://tempuri.org/IARVR/RecognizeSpeechResponse")]
        System.IAsyncResult BeginRecognizeSpeech(byte[] speechToParse, int sampleRate, System.AsyncCallback callback, object asyncState);
        
        string EndRecognizeSpeech(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IARVRChannel : ARChess.ARVR.IARVR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecognizeSpeechCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RecognizeSpeechCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ARVRClient : System.ServiceModel.ClientBase<ARChess.ARVR.IARVR>, ARChess.ARVR.IARVR {
        
        private BeginOperationDelegate onBeginRecognizeSpeechDelegate;
        
        private EndOperationDelegate onEndRecognizeSpeechDelegate;
        
        private System.Threading.SendOrPostCallback onRecognizeSpeechCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ARVRClient() {
        }
        
        public ARVRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ARVRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ARVRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ARVRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RecognizeSpeechCompletedEventArgs> RecognizeSpeechCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ARChess.ARVR.IARVR.BeginRecognizeSpeech(byte[] speechToParse, int sampleRate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRecognizeSpeech(speechToParse, sampleRate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string ARChess.ARVR.IARVR.EndRecognizeSpeech(System.IAsyncResult result) {
            return base.Channel.EndRecognizeSpeech(result);
        }
        
        private System.IAsyncResult OnBeginRecognizeSpeech(object[] inValues, System.AsyncCallback callback, object asyncState) {
            byte[] speechToParse = ((byte[])(inValues[0]));
            int sampleRate = ((int)(inValues[1]));
            return ((ARChess.ARVR.IARVR)(this)).BeginRecognizeSpeech(speechToParse, sampleRate, callback, asyncState);
        }
        
        private object[] OnEndRecognizeSpeech(System.IAsyncResult result) {
            string retVal = ((ARChess.ARVR.IARVR)(this)).EndRecognizeSpeech(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRecognizeSpeechCompleted(object state) {
            if ((this.RecognizeSpeechCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RecognizeSpeechCompleted(this, new RecognizeSpeechCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RecognizeSpeechAsync(byte[] speechToParse, int sampleRate) {
            this.RecognizeSpeechAsync(speechToParse, sampleRate, null);
        }
        
        public void RecognizeSpeechAsync(byte[] speechToParse, int sampleRate, object userState) {
            if ((this.onBeginRecognizeSpeechDelegate == null)) {
                this.onBeginRecognizeSpeechDelegate = new BeginOperationDelegate(this.OnBeginRecognizeSpeech);
            }
            if ((this.onEndRecognizeSpeechDelegate == null)) {
                this.onEndRecognizeSpeechDelegate = new EndOperationDelegate(this.OnEndRecognizeSpeech);
            }
            if ((this.onRecognizeSpeechCompletedDelegate == null)) {
                this.onRecognizeSpeechCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRecognizeSpeechCompleted);
            }
            base.InvokeAsync(this.onBeginRecognizeSpeechDelegate, new object[] {
                        speechToParse,
                        sampleRate}, this.onEndRecognizeSpeechDelegate, this.onRecognizeSpeechCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ARChess.ARVR.IARVR CreateChannel() {
            return new ARVRClientChannel(this);
        }
        
        private class ARVRClientChannel : ChannelBase<ARChess.ARVR.IARVR>, ARChess.ARVR.IARVR {
            
            public ARVRClientChannel(System.ServiceModel.ClientBase<ARChess.ARVR.IARVR> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRecognizeSpeech(byte[] speechToParse, int sampleRate, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = speechToParse;
                _args[1] = sampleRate;
                System.IAsyncResult _result = base.BeginInvoke("RecognizeSpeech", _args, callback, asyncState);
                return _result;
            }
            
            public string EndRecognizeSpeech(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("RecognizeSpeech", _args, result)));
                return _result;
            }
        }
    }
}
